a_b:
  repo: git@github.com:winton/a_b.git
  path: vendor
authlogic:
  repo: git@github.com:winton/authlogic.git
  path: vendor
deploy:
  repo: git@github.com:br/a_b_front_end_deploy
  path: config
lightbox:
  repo: git://github.com/buckwilson/Lightbox_me.git
  path: public/js